---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ceph-csi-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://ceph.github.io/ceph-csi-operator
  timeout: 3m
