apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubedb-catalog
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://charts.appscode.com/stable/
      chart: kubedb-catalog
      version: v2021.04.16
      sourceRef:
        kind: HelmRepository
        name: appscode-charts
        namespace: flux-system