---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: matrix
  namespace: flux-system
spec:
  type: matrix
  address: https://synapse.${SECRET_DOMAIN}
  channel: "TEST-${SECRET_DOMAIN}-${SECRET_FLUX_MATRIX_ROOM_ID}-TEST"
  secretRef:
    name: matrix-token
