---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: matrix
  namespace: flux-system
spec:
  type: matrix
  address: https://synapse.${SECRET_DOMAIN}
  channel: "${SECRET_FLUX_MATRIX_ROOM_ID}"
  secretRef:
    name: matrix-token
