# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: openldap
    namespace: kube-system
type: Opaque
stringData:
    01-default-users.ldif: ENC[AES256_GCM,data:CLE4MLrl6Kv08pskr3pLBRWUdqeRSPgpl5cW57u99Je3vOOD8qjiQ53//8sXYHDN25Sr1n8n4KhQJaL+s4vb1pmt/5bqs7p9lfl96X11g97f3Mt8YH8yjV5lKuJT6mnA3CNAtMIByY1lRCvJM1SqRJYeLyudRmJZoblgs/NQ4KDIBwqPgZMJKPDveIRmSHzTX+V53angaDQVm/wXhbz4ZbcSOKLxtlFXE+jnLn0CNVc/bZQyvolBxtTpsfGmZxPr3In66LZ5b5iqdPyOwrTITKrEdGfWvRwPNIl2YKunMF6EYiGQG8b3i84yqNdHiXQTzYCFiW0riY6e/Q2Wjp6/T9th4OKxnEVrPHBkVbvRZHYBXMBiCZiY4e93JLjR1bCaTSj8NdzELEdRml2qs1ckhBzcWR0OmD1trgVJ20l6tFJHg7Wdpds5xHj2xQB6F4nBSCCYGl73wTR42ymdG4NaeKrAJ//lOEcLJV5Emfj+hOhhKHVnwunncHL7UW1qvkIpazUyRQKanuI/OpqUlvvzTZyaUibX0WmxMaJWL4xe0IXDeNbcGxUC5ewRgxkAY2nB7TdqjZR5/nqkBLMcz//zdxFoyItQtk9dz53bnm4ZTzUIbKLF3BsRnyY5wo0/tv8DJir+cqzn7zGEhyCU+OJlRlERpcuLCUk=,iv:lPThU77riCVzH9mGh4bqiaa4M9lBIjPSUHieLb9BlWo=,tag:NJcTDSk7cwhzqnYgM/dhXg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T02:34:39Z"
    mac: ENC[AES256_GCM,data:mwBfuhr4jj6fcQQfno4cjG394B/Z8nF+iWxR9kAPuYwWDpRiZtNuoLU6MLcoHREFTrx1iR7j5TU4QfHMk1cnm3BlU5IFQpYBG0rIJZ9Katprl3j89ecJvmiv86oCpfdNTVrfuAQ7GNXPMwSZhW3BMJCGxsxeQPLBjmyr34vX4XI=,iv:Nc/IoHkfzNHYb+Rp4nb2R/L/fqCFZrFoW/sXpE96lVk=,tag:azF5mzWn3DoL4iaoI2xEKg==,type:str]
    pgp:
        - created_at: "2024-02-14T18:17:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAARAAwF1+F1Ye4SMqSM4WWBFyBqjZpmKOnY9n1afg2/NfGYDM
            ciuAz1hzvvuWjUu8/EyoVod59FGW4Z+QP29wrs3XQTGjeh5h87ZcEvdByo57qB61
            roz1WFO22wiaspm1ElnAuJw/F+VjGzf2viFrfeLA5SmdEbK4FUUICIAsqiuWib45
            qRRUFV/7ugjS7agwYZXogIqbRgCuD3hfjyVp0bPofKaPro/unNS5LkimI09cgiEk
            otlrEFtjnDOZKSXsJgjj6xB28JOfmnsfP1rR/oEzKe5oiAOP9Qg084DfAN49Ds3O
            XKKDmGy9k3qEm8JQTQj704PDyMOsFTjHFd63SH9WZL+HmR8NIvt9x2JRskOCHj3u
            yfWpn1ZhDVMn5e8qlUprw+hhhPf98B7a+fmaL7I5Re8wfs2oJFCI4PkcFY3NsEux
            n76Q2RlZjYIu1EKTvmMaFH4J2uB0TlwBEro38QftrAQRX7lFp3S5F3AJJkSMgnTO
            3/oJHII5QlgJpY1Nv+N+JxxA1uhmn6sPNsgFvaoQKbzvvjYupRRsXFgOAsWJjbeL
            7kZhvN5fw5nXaZv84XCKOmzH2bihU4zWefxWuQ7RPUTvos7NlYAJvvpEJK/ZPXkJ
            MIKPgmxa+kbb6fgAuPEWUocVBOWBnQcL3fxK6yEdIHHw+TLP3H4ZDTPX9wxWC1HU
            aAEJAhCP5+7/P7tok9yAPUSvU/d7xp+SlNFum+wvGGR04gnXyobGD1WI4Md1aVqD
            4xePNW2q1HrAtNMtWSu4pVjz2ZR2XPhpe8OaWEjmeJMfJIAB0equP1bhT41ae2by
            FN13wZWq2xMB
            =rUvU
            -----END PGP MESSAGE-----
          fp: 1FD2CE4427F19D19F127A2912B144AB1754C9A0A
        - created_at: "2024-02-14T18:17:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAARAAo9xNFnNG6wi40yvw51u/ET579784Dzx3W7PMe1/zWyh2
            zX9s9WqQ/PSgkAqKBA1EG9FKZp2/ID5BUwETCMcq+Zo1Zu2OnTAIv97isXQ9WvyF
            r5wWDZLALwwA/NOjAaJhqfOVfOdy4VSZy7CpT9JBglsvqhv4b+v/e/Mk9INj2ZUJ
            1B7jYBQRVxC0nGxsnfu49Kint+6V86fbGC2SYdmlhX8MUScAfUOtKQ014lZGAYpl
            z095esv2UnOZ1ITmMVuNVnfl4tokWgIEZAcaqMnN/osxz2byx7ftM4qS5QhJQ9yo
            p9MLSrFotzld/WINdg8Z1isdXVgj9T0uY//BnRSCUV29UArDW0ryHFD6+lMoMOMD
            60f+CSS2L5SxkdHhgwLs79grLAArjARxZKKwCxis9ONPN0qWnafJwVl3VOigfzkH
            9VtcZ2HCn1V7lwRB22xmVf8xiE+rmhYW0KitJ02tB/GWVtvCsLEe/kp5YD5AuhVQ
            Tr2inyvTiNFufb2i0RPF/X/JGMdWIzReYOqDzWyZt/HxMKYviIryn10ozsEz2WO3
            s9VOmjWdwmJ9+63gbqkBgm2n1oPhmZyYxpJAgnoO6IGh8xEKuyHUUmn57DMTsf54
            yWd6ymNOmkpPujBKiEv+utDqIxpVZALEcXPrRwblPjNJorhCkZXGhWw8yEXCL6nS
            XgG665GmAkQYoQ7hIP/NTLEjyyUH8bvK9uTH3MV5WG0cfuH1tMEvuKqsXwFOsRwY
            PEifvJjbCdX5XLyCU9q5VWcyXhOqSam7FyY3loTuMXkHEcp7OgqgIeWaevC3zVc=
            =wiGY
            -----END PGP MESSAGE-----
          fp: 21E16B8D2EE875306A6C9968D83077B99F8C6643
    version: 3.13.1
