# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: openldap
    namespace: kube-system
type: Opaque
stringData:
    01-default-users.ldif: ENC[AES256_GCM,data:o/Zojaq+lI0XJMHjqkqTsObRR7ukNe0L9o5+T2WMUCXqGWrD/cbf+PRPipcFwkh0YP+sQW49Nhbti5hC6piKyelf4wAh5CinQPNNaIH8Bi9nyeHIhomrwVPkSOVeJcEJBAb8IYMAAcef3ji4ElAr0FPDPHkqj3iD42XOg/0UnOp8TGGew1WaH4TR800M6hPq2g5fki02V8F7ep7LT/VIC8KkHrnu/amsliUNH9p1J9ymuYWM6Uv0cowoZyB/gp0/bFMqNsd4U4ZckHV7J8RdcpUYTPNlE/McDiYRTiq7feILJx4Elt/euPTUeknmlRwS5A85n2bT/q94IGU65E3DA4FTJsX0FGB9oC2w6Wb6g4f2YL9zJPOiyFh3UjMjT9/rkZSkbv3CYxbhimg3870KK9fngzejT9PJK/QCMXTkxoxShARIhDC3YRx1nrDKulmrRehlr/bkClc5CDhgMi1c//65DBwkebbNxil/eWzSpTOeIEZPkrr5PbLpz0mv8puQkdMN/PxLmafzhoJUhLigyn2MNfMxtnYhDDhaZcfddAhaOfVzawTfycS+9g==,iv:CmgQtOhhsxNIcq0EXYSHM5co6gz8GTrGPU5ZHKFI13k=,tag:ttg7AgpzTqvtAjc/XA0gNA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T02:41:43Z"
    mac: ENC[AES256_GCM,data:LAR+c3oZRqaYBdX2onUZTzE50lGfu1KVX/3o935iTofTZL+l6qkz42EuLecuA9bkor1AH5kOPt/1udtG4l3e+c8NsgIEipbKe6k+8FjNSdklJ2HMjsj43joSHIyqfhSPu8UAQl8ttBa9k/1LZtmrn42bMw5jYdBd/EOjPDhlQkU=,iv:wGj82mYlLjOslEEeryxewbX/a1kAlhcmn4TeSEtP8O8=,tag:E+lknx5gpjUCqaZWsN/qzA==,type:str]
    pgp:
        - created_at: "2024-02-14T18:17:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAARAAwF1+F1Ye4SMqSM4WWBFyBqjZpmKOnY9n1afg2/NfGYDM
            ciuAz1hzvvuWjUu8/EyoVod59FGW4Z+QP29wrs3XQTGjeh5h87ZcEvdByo57qB61
            roz1WFO22wiaspm1ElnAuJw/F+VjGzf2viFrfeLA5SmdEbK4FUUICIAsqiuWib45
            qRRUFV/7ugjS7agwYZXogIqbRgCuD3hfjyVp0bPofKaPro/unNS5LkimI09cgiEk
            otlrEFtjnDOZKSXsJgjj6xB28JOfmnsfP1rR/oEzKe5oiAOP9Qg084DfAN49Ds3O
            XKKDmGy9k3qEm8JQTQj704PDyMOsFTjHFd63SH9WZL+HmR8NIvt9x2JRskOCHj3u
            yfWpn1ZhDVMn5e8qlUprw+hhhPf98B7a+fmaL7I5Re8wfs2oJFCI4PkcFY3NsEux
            n76Q2RlZjYIu1EKTvmMaFH4J2uB0TlwBEro38QftrAQRX7lFp3S5F3AJJkSMgnTO
            3/oJHII5QlgJpY1Nv+N+JxxA1uhmn6sPNsgFvaoQKbzvvjYupRRsXFgOAsWJjbeL
            7kZhvN5fw5nXaZv84XCKOmzH2bihU4zWefxWuQ7RPUTvos7NlYAJvvpEJK/ZPXkJ
            MIKPgmxa+kbb6fgAuPEWUocVBOWBnQcL3fxK6yEdIHHw+TLP3H4ZDTPX9wxWC1HU
            aAEJAhCP5+7/P7tok9yAPUSvU/d7xp+SlNFum+wvGGR04gnXyobGD1WI4Md1aVqD
            4xePNW2q1HrAtNMtWSu4pVjz2ZR2XPhpe8OaWEjmeJMfJIAB0equP1bhT41ae2by
            FN13wZWq2xMB
            =rUvU
            -----END PGP MESSAGE-----
          fp: 1FD2CE4427F19D19F127A2912B144AB1754C9A0A
        - created_at: "2024-02-14T18:17:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAARAAo9xNFnNG6wi40yvw51u/ET579784Dzx3W7PMe1/zWyh2
            zX9s9WqQ/PSgkAqKBA1EG9FKZp2/ID5BUwETCMcq+Zo1Zu2OnTAIv97isXQ9WvyF
            r5wWDZLALwwA/NOjAaJhqfOVfOdy4VSZy7CpT9JBglsvqhv4b+v/e/Mk9INj2ZUJ
            1B7jYBQRVxC0nGxsnfu49Kint+6V86fbGC2SYdmlhX8MUScAfUOtKQ014lZGAYpl
            z095esv2UnOZ1ITmMVuNVnfl4tokWgIEZAcaqMnN/osxz2byx7ftM4qS5QhJQ9yo
            p9MLSrFotzld/WINdg8Z1isdXVgj9T0uY//BnRSCUV29UArDW0ryHFD6+lMoMOMD
            60f+CSS2L5SxkdHhgwLs79grLAArjARxZKKwCxis9ONPN0qWnafJwVl3VOigfzkH
            9VtcZ2HCn1V7lwRB22xmVf8xiE+rmhYW0KitJ02tB/GWVtvCsLEe/kp5YD5AuhVQ
            Tr2inyvTiNFufb2i0RPF/X/JGMdWIzReYOqDzWyZt/HxMKYviIryn10ozsEz2WO3
            s9VOmjWdwmJ9+63gbqkBgm2n1oPhmZyYxpJAgnoO6IGh8xEKuyHUUmn57DMTsf54
            yWd6ymNOmkpPujBKiEv+utDqIxpVZALEcXPrRwblPjNJorhCkZXGhWw8yEXCL6nS
            XgG665GmAkQYoQ7hIP/NTLEjyyUH8bvK9uTH3MV5WG0cfuH1tMEvuKqsXwFOsRwY
            PEifvJjbCdX5XLyCU9q5VWcyXhOqSam7FyY3loTuMXkHEcp7OgqgIeWaevC3zVc=
            =wiGY
            -----END PGP MESSAGE-----
          fp: 21E16B8D2EE875306A6C9968D83077B99F8C6643
    version: 3.13.1
