---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: kube-system
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/vegardit/openldap:2.6.10@sha256:fd9af3fd925cda6409ea62156ce9002798bcc4c86eddc4178f137888a2e176d4
          imagePullPolicy: "Always"
          env:
            - name: LDAP_INIT_ORG_DN
              value: ${SECRET_LDAP_BASE_DN}
            - name: LDAP_INIT_ROOT_USER_DN
              value: cn=${SECRET_LDAP_ADMIN_USERNAME},${SECRET_LDAP_BASE_DN}
            - name: LDAP_INIT_ROOT_USER_PW
              value: ${SECRET_LDAP_ADMIN_PASSWORD}
            - name: LDAP_TLS_ENABLED
              value: "false"
            - name: LDAP_LDAPS_ENABLED
              value: "false"
          ports:
            - name: tcp-ldap
              containerPort: 389
          volumeMounts:
            - name: org-entries-ldif
              mountPath: "/opt/ldifs/init_org_entries.ldif"
              subPath: init_org_entries.ldif
              readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
      volumes:
        - name: org-entries-ldif
          secret:
            secretName: openldap
            items:
              - key: 01-default-users.ldif
                path: init_org_entries.ldif
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: kube-system
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 1389
      targetPort: tcp-ldap
  selector:
    app.kubernetes.io/name: openldap
