---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  releaseName: nzbget
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts/
      chart: app-template
      version: 5.1.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/nzbget
              pullPolicy: IfNotPresent
              tag: 26.2.20260821@sha256:1dca6a4407e08313919d2780bf2a6bc17e21b947a6e8e34624b9e115795fcf8c
            env:
              TZ: America/Chicago
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 512Mi

    service:
      main:
        controller: main
        ports:
          http:
            port: 6789

    route:
      main:
        hostnames:
          - nzbget.k.${SECRET_DOMAIN}
        parentRefs:
          - namespace: kube-system
            name: internal
            sectionName: https

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "Always"

    persistence:
      config:
        enabled: true
        existingClaim: nzbget-config-pvc
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        globalMounts:
          - path: /media
      incomplete:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /incomplete
