---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: nzbget
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbget
      tag: v21.0
    service:
      type: LoadBalancer
      loadBalancerIP: 10.10.40.64
    env:
      TZ: "America/Chicago"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx-internal"
      hosts:
      - host: nzbget.k.homelab.tokyo
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "nzbget.k.homelab.tokyo"
    persistence:
      config:
        enabled: true
        storageClass: "longhorn"
        size: 20Gi
      media:
        enabled: true
        existingClaim: nfs-media-pvc
      downloads:
        enabled: true
        emptyDir: 
          enabled: true
        mountPath: /downloads
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    # podAnnotations:
    #   backup.velero.io/backup-volumes: config
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    resources:
      requests:
        memory: 300Mi
        cpu: 100m
      limits:
        memory: 1000Mi
