name: Sync Repository
run-name: Sync Repository at commit ${{ github.ref }}
on:
  push:
    branches:
    - main
jobs:
  Sync-Repository:
    runs-on: alpine-tokyo
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup SSH
        uses: actions/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: |
            ${{ secrets.SYNC_KEY }}
            ${{ secrets.SRHT_SYNC_KEY }}
      - name: Prep Remotes
        run: |
          cd ${{ github.workspace }}

          # Ignore hosts keys, since we accept them as-is, add remotes
          git config --global core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          git remote add github git@github.com:${{ github.repository }}.git
          git remote add codeberg git@codeberg.org:${{ github.repository }}.git
          git remote add gitlab git@gitlab.com:${{ github.repository }}.git
          git remote add sourcehut git@git.sr.ht:~${{ github.repository }}
      - name: Push Code
        run: |
          cd ${{ github.workspace }}

          git push github ${{ github.ref_name }}
          git push codeberg ${{ github.ref_name }}
          git push gitlab ${{ github.ref_name }}
          git push sourcehut ${{ github.ref_name }}
