apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: registry-creds-controller
  name: registry-creds-registry-creds-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: registry-creds-controller
  template:
    metadata:
      labels:
        control-plane: registry-creds-controller
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /controller
        image: ghcr.io/alexellis/registry-creds:0.2.7
        imagePullPolicy: IfNotPresent
        name: controller
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 45Mi
      terminationGracePeriodSeconds: 10
      tolerations:
      - key: arm
        operator: Exists
