---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-redis
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 13.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    configmap: |-
      # Add an ACL File configuration to allow for ACL based auth (required by Authelia helm chart now)
      aclfile /etc/redis/users.acl
    master:
      persistence:
        storageClass: "longhorn"
        size: 1Gi
    slave:
      persistence:
        storageClass: "longhorn"
        size: 1Gi
    extraVolumes:
      - name: aclfile
        secret:
          secretName: authelia-redis-aclfile
    extraVolumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/etc/redis"
  valuesFrom:
  - kind: Secret
    name: authelia-redis-helm-values