apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-helm-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgAprl+FNtQLGo3AniaZeZVPiuzRZ0rydj2Y3/BH9ck9RvVbYzaMQhX7bSD9lSqvmxD8/ai9dhVkPRKYibRL61nIMA0lNWEb6jPjdEoIc2UOUfsVw3CZwjdNj11BBH1ULSu1UNkB1Iw3ZeXVldohhWtFQsqKqatzM2mHinCGxqN4tMwPY5DXmkHEBxQAoy02jzGBLqLUB2JoKUOk8HgjAZ3enwaIv4gkdYHLgZK4ZHqIIdg2UaBPoASszB0IfW2agHEYnf98VCqH9BIBt6/t2ecpQ0cUFo71Zq1wdJQpgAGfH2SDBDphOtkqfg+iZLbEZ523ZTfyXPM9t6bz9cRR2zeZ4Z1jRiv4SiUAfH4WuWNW1qw71knHrzPAOGAGiLLDqWPCsSsN6Go0bh5fBtqZ94ZcGDeJseEThE0BwhmSwnL5GMS/5SdGE9d4kxiBLTYSU/nYxMqVlUDY60vGK2zmFq4yILb+AOYxGV3nFG5IZUGuGZCKXY8CB4fLX2k+zjhROjkeu7GryBBMyMuTHfI86FEHpWPU3gER/qY4n149aN/16O3iBLTmahbDzldhQnRlekrAXbhdfMPGxYMyrT2GZNXdL6mPYYTvhJCLqXeeSbT+a5vSPYRBsfNDEsU9swnyRi89J/f5u7rkmWs7gb5NQEMbK/0BIW4jHCjscFpd4RTyJcHExq1PuzPq9Wl+wl+GBWfCjpAVLvtAMu34quJPdJZtgVAXMdCxBQQkg15DXlQNU7MK27nCu/qTnS77pzjrDuA3AGp1QHmSy3Ldo60ecpIDX3vqz1I5kRtQ/5ekZ+2Q53QB7//SHpkE4J0uLRlx3Ng=
  template:
    metadata:
      creationTimestamp: null
      name: authelia-helm-values
      namespace: kube-system
    type: Opaque

