apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-redis-password
  namespace: kube-system
spec:
  encryptedData:
    password: AgAer9+LaV6rAfExk+FJGITHCIA0mEWcEpGqo5bLM9nGjwpeYvbfDiNFTBjnV/9SmTYOhFfnx3KSKh86KdQLzle7W3C616KT7SgkN5VZoewXIfcNTqg94Y9VRvB/LmXLPpyM7zmhLRPSD1MHcvjfrp9AgZ+oQJQJg68N041Rc618VcqkW4rF+e8RdMIpADUSYBhg7IG2hnqtWA1sCQVPeszxzD4qeKxtEwbcNGwDeP7TXKQsPxSCT/KxKrawglCtkkXI5ZKLC/nH6kjrafAXdEk92LnBLrr2iaMdEeHIHh1AZBlld3WwKuDdx/k39Hki+aVUJKZCDPtmn8v2uz1N8ar1j6dvs/IfsvBfWT2mG7mAPO1dmywATf/7/RlallYz+9UDe1UlJD/2krtyuLwwpceD84cs2sNvQrb8YJDknxxMAuQIsCWJNS6fkmtXrzkJ1OvvmdDvdB2SFJPATi5RAsxW1JYhQl+xBp369GSoXQegYhIFx3oc7IOfqK/yLEsMS6jl1m5el4mYaME1BCUYdAA4urzqZYy81qsPaU03BqX6xzrX5cxBWT4srIivGIQoloXdqe8sk8a7LDJP1E7WbMxfcwPdE1gK58u7OyqubFt8QvCLmYEYxxSlnbJmnHBd5wbiEZI6W5rlcxF2gbf+hDlCVkiKlLj9e2w7EzopkMb0y273b1HdV5u6VDL+4RVt92qtZ2O/vslmXyY5WC1exQlMg2ILO5eC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: authelia-redis-password
      namespace: kube-system
    type: Opaque

