---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-postgres
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 10.5.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      storageClass: "longhorn"
      size: 2Gi
    postgresqlUsername: authelia
    postgresqlDatabase: authelia
    nodeSelector:
      matchExpressions:
        - {key: k3s.io/hostname, operator: In, values: ["k3s-amd64-a", "k3s-amd64-c"]}
  valuesFrom:
  - kind: Secret
    name: authelia-postgres-helm-values