---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: flood
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jesec/flood
      tag: 4.5.4
    env:
      FLOOD_OPTION_RUNDIR: /config
      FLOOD_OPTION_AUTH: "none"
      FLOOD_OPTION_RTSOCKET: "/tmp/rtorrent.sock"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-signin: https://auth.homelab.tokyo
        nginx.ingress.kubernetes.io/auth-url: https://auth.homelab.tokyo/api/verify
      hosts:
      - host: flood.k.homelab.tokyo
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "flood.k.homelab.tokyo"

    persistence:
      data:
        enabled: true
        existingClaim: nfs-media-pvc
        accessMode: ReadWriteMany
        size: "1Gi"
      config:
        enabled: true
        size: 1Gi
        storageClass: longhorn

    probes:
      liveness:
        enabled: true
        initialDelaySeconds: 30
        failureThreshold: 5
        timeoutSeconds: 10
      readiness:
        enabled: true
        initialDelaySeconds: 30
        failureThreshold: 5
        timeoutSeconds: 10
      startup:
        enabled: true
        initialDelaySeconds: 5
        failureThreshold: 30
        periodSeconds: 10

    # podAnnotations:
    #   backup.velero.io/backup-volumes: config

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi

    additionalVolumeMounts:
      - mountPath: /tmp
        name: socket

    additionalContainers:
      - name: rtorrent
        # image: billimek/alpine-rtorrent:0.9.8-1
        image: billimek/rtorrent:latest
        env:
        - name: TZ
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: bt
          timeoutSeconds: 1
        ports:
        - containerPort: 49161
          name: bt
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: bt
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 50Mi
        startupProbe:
          failureThreshold: 60
          periodSeconds: 10
          initialDelaySeconds: 5
          successThreshold: 1
          tcpSocket:
            port: bt
          timeoutSeconds: 1
        tty: true
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
        - mountPath: /session
          name: data
          subPath: .session
        - mountPath: /watch
          name: data
          subPath: watch
        - mountPath: /download
          name: data
          subPath: torrents
        - mountPath: /socket
          name: socket

    additionalVolumes:
      - emptyDir: {}
        name: socket

    service:
      additionalServices:
        - enabled: true
          nameSuffix: bt
          type: LoadBalancer
          port:
            port: 49161
            name: bt
            protocol: TCP
            # targetPort: bt
          loadBalancerIP: 10.10.40.65
