---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: envoy-gateway
  namespace: kube-system
spec:
  selector:
    matchLabels:
      control-plane: envoy-gateway
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: metrics
      path: /metrics
      honorLabels: true
