---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: mastodon-valkey
  namespace: social
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
      app.kubernetes.io/instance: mastodon-valkey
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames:
      - social
  endpoints:
    - port: http-metrics
      path: /metrics
      honorLabels: true
