apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-secrets
  namespace: media
spec:
  encryptedData:
    plex-claim: AgCslGoIqc+oawwdDKPHG3r79Iq+nyvFiPdJiF/DwmxTDqtfuASg8q+1OzKmHNPrcOKUDMlRArOC2XJFua2dJQHEMpvX4iaJ/E7WN4sVC1K9cqya02u23pOoC03BgcJkhXX3ChziYGTVl8mlz5ENKUKz7HqviwDAfOZMqWmZOE26Di0HoGuPbVURy5BvfZ2dmCj6c63ymAT3Cya3o8SvjnP4DNhIqFbSuQylTP/68a9Yh4Ou5j1L/eAlstBtW/RLeEaRNXGeglCfsqn0Z6PF4OeF9RXLj1f26RJhFwXhqi+FUwUeAwG/DPdTOfWMDcQE/rdCpDE2ugERrqS2+ueotzHUsss+30tA6Hc3hAP7Y3du9Ro0cxqcAGTyU5kdcveSAmnvV35cc+89PgdiVaPacvZ20Gv+AKJrcI72b/dgO5l/8JD4HOdOGSokN2KkAl84xzx1YzCFXozHBcplrLa+R3Pk7Ey8HKMShgXLzDjsffLUagYvKhMiJugBcdDkKgrJV9QjXal1rGg2pFRJwjCPrRGweNVZKjCGkKATCtihvE0sev1+OEXBtmUgMqeavDWLNvhkBDkY6XHZuGAN+6iF6rusQDpI4AJppyE76RW7JZAsLYAiWGFs6Zboex5847M1bDSKfWxq2ERsCaouqkV/r45sFe0hwsVgXPFIPKiWcbhz//2ziZRBHW0Y5HlpKUpqVdsVcJcll3u/8Hj+FC8MntvnTr5dVoghEKVNeA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: plex-secrets
      namespace: media
    type: Opaque

