apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: metallb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.9.6
  valueFileSecrets:
  - name: "metallb-values"
