---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: copyparty
  namespace: media
spec:
  releaseName: copyparty
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts/
      chart: app-template
      version: 5.0.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/9001/copyparty-ac
              pullPolicy: IfNotPresent
              tag: 1.20.18@sha256:59fe48c65b5f527c98abf0dfb9eb59e4177923c6a97287974524a6dacc0dbea7
            env:
              TZ: America/Chicago
              PRTY_NO_TLS: 1
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi

    service:
      main:
        controller: main
        ports:
          http:
            port: 3923

    route:
      main:
        hostnames:
          - copyparty.k.${SECRET_DOMAIN}
        parentRefs:
          - namespace: kube-system
            name: internal
            sectionName: https

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "Always"

    persistence:
      config:
        enabled: true
        existingClaim: copyparty-config-pvc
        globalMounts:
          - path: /cfg
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        globalMounts:
          - path: /w/media
