---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewatch
  namespace: monitoring
spec:
  releaseName: kubewatch
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      main:
        type: deployment
        replicas: 1
        serviceAccount:
          name: kubewatch
        pod:
          automountServiceAccountToken: true
        containers:
          main:
            # renovate: datasource=docker depName=robustadev/kubewatch
            image:
              repository: docker.io/robustadev/kubewatch
              tag: v2.15.0
            env:
              KW_CONFIG: /config
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
    persistence:
      config:
        type: configMap
        name: kubewatch-config
        globalMounts:
          - path: /config/.kubewatch.yaml
            subPath: .kubewatch.yaml
            readOnly: true
