---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-csi-operator-image-set-configmap
  namespace: rook-ceph
data:
  provisioner: registry.k8s.io/sig-storage/csi-provisioner:v6.2.0
  attacher: registry.k8s.io/sig-storage/csi-attacher:v4.12.0
  resizer: registry.k8s.io/sig-storage/csi-resizer:v2.1.0
  snapshotter: registry.k8s.io/sig-storage/csi-snapshotter:v8.5.0
  registrar: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.17.0
  plugin: quay.io/cephcsi/cephcsi:v3.17.0
  addons: quay.io/csiaddons/k8s-sidecar:v0.14.0
---
apiVersion: csi.ceph.io/v1
kind: OperatorConfig
metadata:
  name: ceph-csi-operator-config
  namespace: rook-ceph
spec:
  driverSpecDefaults:
    imageSet:
      name: rook-csi-operator-image-set-configmap
    nodePlugin:
      kubeletDirPath: /var/lib/kubelet
      tolerations:
        - key: arm
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: Exists
    controllerPlugin:
      hostNetwork: true
---
apiVersion: csi.ceph.io/v1
kind: Driver
metadata:
  name: rook-ceph.rbd.csi.ceph.com
  namespace: rook-ceph
spec:
  liveness:
    metricsPort: 8080
