---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: synapse-psql-v17
  namespace: default
spec:
  # daily, 3am UCT
  schedule: "0 0 3 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: synapse-psql-v17
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: shared-psql-v18
  namespace: default
spec:
  # daily, 4:30am UCT
  schedule: "0 30 4 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: shared-psql-v18
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: mastodon-psql-v18
  namespace: default
spec:
  # daily, 2:30am UCT
  schedule: "0 30 2 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: mastodon-psql-v18