apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: botkube-helm-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCYwd5ML03rjalY2+80UOR6wAZO+9elZvloZkE58Io4Q5asUYba4BCmxIc26zhnQdVDsksu407xma4+udyNpw5waKVmmCt6qsMNwmug/wv17Qgdy5R8kTxsZHJ9urW/ew3Rwnfw8v+W/xZbLT5l3iaePzvoyOH2RpRAsbnIjSOVdgzF09v8EpSmBCDFttgW02laUGkWeuHx0WbbdyzjTgnDwbQE7YzTQyQYwgjTcLcsmsn8ECxfouIhEyF4VDpuVwMKLe2jQtDP6ge7Y9/22PLfrIqdeIJ2arlj3sLX2lJDszH4rkSwTddpNDHnI3iBq5VSdJW1zwe0WsTmcCkql4jabHirkxQYV+cV/wmTU4CPDG4+3bk6U8vRTirjHVAK9SIfN8h9gfTdqnU79bRzXbO9bLkYEiZEAeAk5Zk3s7kbRJtuwGYnLEIAD1i6HUsrIYpxi0wJhp9rutmziGhLyd3bS+WsWwimqa5E6UEO6ndoh6qsXmeqcb6bzdxzhpYhjp//RK98GWtVsUB1MDTxJdwhKqLB/SKu1gn8Kbb6m40ic3SxyjSRGtOCBYAG2T7KmOFIdEXOUyB2a7pzT3bF3Fd32HXmToLzMR7zcOhqHb8IzPW3BmhFLM3uETthyVe7EIZ1FOxzHlBpTOKUWIyFSQyoiZEAlJQ3/DvRI8Yzh/RqWk+aZH/qaxCgWZYgOyC7NO757o0QNOi0+jQhW3Otf/j3unGeyi+1AQTKj6AYuTvRnMufvWko/1StUPy+EpqWqHdd9bWlrqLTZvAoHqbpmYTeqkIler8i6wtAwEITtoj6aiVmwbE1ou0V8z+2ddjrFJASCWlUmf2bxb0b28JZXYCi/mkMhnlblS7mYbpRcGn5u35TEFdugXN/ecvdQQJw3GdOvcNfYM/0Raulg8WR7xO4wRmJV9b3ChMatnBcT54joM9T4VT1RyJa4yQQh7OzRUgdH6gb+fBikgb3Who7
  template:
    metadata:
      creationTimestamp: null
      name: botkube-helm-values
      namespace: monitoring
    type: Opaque

