---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: default
spec:
  releaseName: immich
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 0.13.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: immich-charts
        namespace: flux-system
  values:
    controllers:
      main:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.6
            env:
              INIT_POSTGRES_HOST: shared-psql-v18-rw.default.svc.cluster.local
              INIT_POSTGRES_SUPER_PASS: ${SECRET_CNPG_SUPER_PASS}
              INIT_POSTGRES_DBNAME: immich
              INIT_POSTGRES_USER: immich
              INIT_POSTGRES_PASS: ${SECRET_IMMICH_DB_PASSWORD}
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v3.1.0
            env:
              DB_HOSTNAME: shared-psql-v18-rw.default.svc.cluster.local
              DB_USERNAME: immich
              DB_DATABASE_NAME: immich
              DB_PASSWORD: ${SECRET_IMMICH_DB_PASSWORD}
    immich:
      persistence:
        library:
          existingClaim: nfs-immich-pvc
    valkey:
      enabled: true
      persistence:
        data:
          type: persistentVolumeClaim
          existingClaim: immich-valkey
      controllers:
        main:
          containers:
            main:
              resources:
                requests:
                  cpu: 10m
                  memory: 16Mi
                limits:
                  memory: 64Mi
    server:
      ingress:
        main:
          enabled: false
      route:
        main:
          enabled: true
          kind: HTTPRoute
          hostnames:
            - photos.${SECRET_DOMAIN}
          parentRefs:
            - name: external
              namespace: kube-system
              sectionName: https
      defaultPodOptions:
        nodeSelector:
          intel.feature.node.kubernetes.io/gpu: "true"
        resourceClaims:
          - name: gpu
            resourceClaimTemplateName: immich-server-gpu
      rawResources:
        gpu:
          forceRename: immich-server-gpu
          manifest:
            apiVersion: resource.k8s.io/v1
            kind: ResourceClaimTemplate
            spec:
              spec:
                devices:
                  requests:
                    - name: gpu
                      exactly:
                        deviceClassName: gpu.intel.com
      controllers:
        main:
          containers:
            main:
              resources:
                claims:
                  - name: gpu
                requests:
                  cpu: 50m
                  memory: 768Mi
                limits:
                  memory: 2Gi
    machine-learning:
      defaultPodOptions:
        nodeSelector:
          intel.feature.node.kubernetes.io/gpu: "true"
        resourceClaims:
          - name: gpu
            resourceClaimTemplateName: immich-ml-gpu
      rawResources:
        gpu:
          forceRename: immich-ml-gpu
          manifest:
            apiVersion: resource.k8s.io/v1
            kind: ResourceClaimTemplate
            spec:
              spec:
                devices:
                  requests:
                    - name: gpu
                      exactly:
                        deviceClassName: gpu.intel.com
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                tag: v3.1.0-openvino
              probes:
                liveness:
                  spec:
                    periodSeconds: 10
                    timeoutSeconds: 5
                    failureThreshold: 60
                readiness:
                  spec:
                    periodSeconds: 10
                    timeoutSeconds: 5
                    failureThreshold: 60
              resources:
                claims:
                  - name: gpu
                requests:
                  cpu: 50m
                  memory: 2Gi
                limits:
                  memory: 6Gi
