apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route53-api-key
  namespace: cert-manager
spec:
  encryptedData:
    key: AgDNaT/Ba3uFJhYtVeM2K2RSsUeQ32feegGZc5GiuR35DrUXcGboUeo7FYTYUgRowzDJlLj0p1mKqj0MSu+e52jQmf+rxWaidu51hp5i7Yx4sfhIjb4ZXPnyl1E2rvWWwN8t91bbQ2cWlbtQQMpPHoSf13ftloOqIfR1S2cC3Ixz/7YzDYYiN5tFvud471y1rMLuGtLz9R6c9JhwN9gl0eAdJeYh4UAa7KIvIyNnAn9sBhqen8uNPHegjjcKD5QFkW1oGmY7BJh7WoiEQur+GVSNa/OjLFkC2a4M4tPCyB3QIMn2JhoQcXZi6+7ldHCiwhIMM3KPMe35IP1eh9Yiry/e1HG3W9CREINaTw1no0WoUiDbxwr4gv/Zd8tCopQNBo6PE9cZgiAh2SxHy/SC+/oHfiIYDJizadWbLCF4IElBgk6E145l+hOPqM/7CarsLo//x/pwWBR5R1J4Mh6S7CbEEHYc87yf7j1q10T1Kr2Zawb0ipyzDgf63Z0CsI4wjm10ew2TWwFmq8M0Th9nlazuDiLELRmpUGubpQiCq9oelwCjIdXG5kRFlbIFgOaVbbSQhBFexKj2wcA/d667nev3/ko4pA6PoHabPpWdgopKYLyT1qVCRBJBn3+oUecJABxUGGNbxKJjcMHVIDdCWLwi2BVK9BEGWBkHY1SIWCSPR+XfrWOJogWEJ3AtECRLmJ6VmFB+i5gUMm6m6hFR8PEAjumm9mq5zDd7XRpR2qU1gGELCw0MEdC7
  template:
    metadata:
      creationTimestamp: null
      name: route53-api-key
      namespace: cert-manager
    type: Opaque

