apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBPfu0fLIOHbCIzyd4Q1TqomvGsQHYoffRiGWhMsXVydWpz645v/tJO4edEdmCk1Yg6FVgzLN2yTj4ntWoEDtA2aPs2QDTQG0O3rHvYEWJS/FkCAV0+ymaSmKisS7kjijy4bLopPu6yhyAT+2VDBHABS06rFDTsDb0dqd8Uvqr1idziDx9oe+LaUPQNgcH/O9IcwPLLGRwj3nNMfYuonARtByqzfsLYva0p8eNKbnYz6rHatSfvnlBgvYOr9HFxWDelH7dLqXQ1DEhdgWGajiavUSeoMCcFyH0Ov/v3RIwHFoR8gy1DPcv0nH6fprpTSMWpylz2YMtz/tPan6Cczkn6/n91+ytHwKwSq7lV9dCAHXGLY9CyJWcLPdhOVrGhuZsdTwx4J2XJ9/0+nxO8/mDTgdUaFiCpFS3h+SzlFWvJ7sajTxqjm7e5tVcyeHlLqjjnorYYv0s9jDCsZe+Z7RDhODuX3QT4FuzWZqTto1ZiYu6WBPUZF/YKRYgc0qBmsu3urs+K1xH/ra1kzduq7d4oo/BiQggPVlEF9CWUvy76CA8hqtuzdzTPd0PynFuY3NHJWt5DRtAKK7SQMUxsyM4rUdt0dbXo6uO4Z6EnLXeWcpGOqn0KcEUVF1sqvyafeOGCiLOMXx7Oesf398swJ70RfUIiaac7+dOM3+vAQyZDrlchg/9iSxCnagtUjSbl1LH38dW1HNaXI7U7nlB5dnM7NcH1/DiBR850e6GClVP/QqexshFBvF9HBsjDgORQEjaIz3U7t/wzs8tB12lYd8eKjPfuEqKtFWoT2cFMspo2ifHlVY2S08O11d5knAjo/hrs8CB01BrOjLViHvpRldQxciB9Cq5V3fSrSwesVoV5+prNfY5Mg1itMWQD/mxE1ZlAH4Tf0l/K3ynB9haKOvE1bLLgvlN5r/ybWA2wDg9N

